export class AnswerKeys{
    dictionary: {index: number, key: number}[];

    constructor(){
        this.dictionary = [
            {index: 0, key: 1},
            {index: 1, key: 0},
            {index: 2, key: 2},
            {index: 3, key: 1},
            {index: 4, key: 1},
            {index: 5, key: 2},
            {index: 6, key: 0},
            {index: 7, key: 0},
            {index: 8, key: 1},
            {index: 9, key: 2},
            {index: 10, key: 0},
            {index: 11, key: 1},
            {index: 12, key: 0},
            {index: 13, key: 2},
            {index: 14, key: 1},
            {index: 15, key: 1},
            {index: 16, key: 0},
            {index: 17, key: 2},
            {index: 18, key: 0},
            {index: 19, key: 0},
            {index: 20, key: 1},
            {index: 21, key: 1},
            {index: 22, key: 2},
            {index: 23, key: 2},
            {index: 24, key: 1},
            {index: 25, key: 0},
            {index: 26, key: 1},
            {index: 27, key: 0},
            {index: 28, key: 0},
            {index: 29, key: 2},
            {index: 30, key: 2},
            {index: 31, key: 1},
            {index: 32, key: 0},
            {index: 33, key: 1},
            {index: 34, key: 1},
            {index: 35, key: 2},
            {index: 36, key: 1},
            {index: 37, key: 1},
            {index: 38, key: 0},
            {index: 39, key: 2},
            {index: 40, key: 1},
            {index: 41, key: 0},
            {index: 42, key: 0},
            {index: 43, key: 2},
            {index: 44, key: 0},
            {index: 45, key: 2},
            {index: 46, key: 1},
            {index: 47, key: 2},
            {index: 48, key: 1},
            {index: 49, key: 2}
        ]
    }
}